e2e-tests/pom.xml, e2e-tests/src/main/java/dev/streamx/cli/test/tools/ResourcePathResolver.java, e2e-tests/src/main/java/dev/streamx/cli/test/tools/validators/HttpValidator.java, e2e-tests/src/main/java/dev/streamx/cli/test/tools/validators/ProcessOutputValidator.java, e2e-tests/src/test/java/dev/streamx/cli/StreamxCliPublicationIT.java, e2e-tests/src/test/resources/application.properties, e2e-tests/src/test/resources/filtered/overridden-nginx-conf, e2e-tests/src/test/resources/filtered/streamx-mesh.yml
covering by tests composite mesh with nginx
=> [DXP-850] add tests covering streamx composite mesh

core/src/main/java/dev/streamx/cli/SchemaProvider.java, core/src/main/java/dev/streamx/cli/exception/UnknownChannelException.java, core/src/main/java/dev/streamx/cli/ingestion/BaseIngestionCommand.java, core/src/main/java/dev/streamx/cli/ingestion/publish/IngestionMessageJsonFactory.java, core/src/main/java/dev/streamx/cli/ingestion/publish/PublishCommand.java, core/src/main/java/dev/streamx/cli/ingestion/unpublish/UnpublishCommand.java, core/src/main/java/dev/streamx/cli/run/MeshDefinitionResolver.java, core/src/test/java/dev/streamx/cli/ingestion/BaseIngestionCommandTest.java, core/src/test/java/dev/streamx/cli/ingestion/IngestionArgumentsValidationTest.java, core/src/test/java/dev/streamx/cli/ingestion/publish/PublishCommandTest.java, core/src/test/java/dev/streamx/cli/ingestion/publish/PublishPayloadCommandTest.java, core/src/test/java/dev/streamx/cli/ingestion/unpublish/UnpublishCommandTest.java, core/src/test/resources/filtered/mesh.yml, e2e-tests/src/test/resources/filtered/mesh.yml, pom.xml
Fetch schema before each publish message.
This PR has to be check by e2e tests based on docker images when their will be released
=> [DXP-1186] Adjust published messages to new messages sending way

.github/pull_request_template.md
Add PR template (as a duplicate of already approved in [streamx](https://github.com/streamx-dev/streamx/blob/main/.github/pull_request_template.md) repository).
=> DXP-1267 Add pull_request_template.md

pom.xml
* Bumping Pulsar version started within `streamx run` to 4.0.0.
=> [DXP-1226] bump pulsar version to 4.0.0

core/src/main/java/dev/streamx/cli/run/RunCommand.java, core/src/main/java/dev/streamx/cli/run/RunningMeshPropertiesGenerator.java, core/src/test/resources/filtered/mesh.yaml, e2e-tests/src/test/resources/filtered/mesh.yaml, pom.xml
Here give description of the changes you've made in this pull request focusing on what is added or changed. 
For example:
* **Breaking change**: `old-property` renamed to `new-property`.
* **Non-braking change**: Added support for `new-feature`.
=> [DXP-1263] Remove tenant from StreamX Mesh YAML

.github/workflows/helper-release-jira.yaml, .github/workflows/release.yaml
Release artifacts and docker images action will update released version in related jira tickets
=> [DXP-1209] Add GH action to put release version into jira ticket

pom.xml
Here give description of the changes you've made in this pull request focusing on what is added or changed. 
For example:
* **Breaking change**: `old-property` renamed to `new-property`.
* **Non-braking change**: Added support for `new-feature`.
=> [DXP-1404] bump StreamX to 1.0.1

core/src/main/java/dev/streamx/cli/StreamxCommand.java, core/src/main/java/dev/streamx/cli/command/manager/ManagerCommand.java
* Reorder Commands to change displayed `streamx help` output:
=> [DXP-1322] Fixes after docs

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
* **Add bug issue template**
* **Add feature issue template**
* **Add contact links**
=> [DXP-1419] Add issue template configuration

core/src/test/java/dev/streamx/cli/config/ConfigSourcesOrdinalTest.java, core/src/test/java/dev/streamx/cli/config/DotStreamxConfigSourceTest.java, e2e-tests/src/test/java/dev/streamx/cli/StreamxCliPublicationIT.java, pom.xml
=> [DXP-1500] Unblock bumping maven resolver by fixing test cases.

core/src/test/resources/dev/streamx/cli/command/cloud/deploy/servicemeshes.streamx.dev-v1.yml, pom.xml
StreamX Operator API version update
=> [DXP-1325] StreamX Operator API update

pom.xml
=> [DXP-1506] Bump StreamX version

.github/workflows/temporary-jira-release.yaml
Add temporary action for jira release
=> [DXP-1470] Add temporary jira release action

.github/workflows/release.yaml
Run jira release on JReleaser release
=> [DXP-1470] add jira release as a JReleaser release action step

core/src/main/java/dev/streamx/cli/command/ingestion/IngestionMessageJsonFactory.java, core/src/main/java/dev/streamx/cli/command/ingestion/batch/BatchCommand.java, core/src/main/java/dev/streamx/cli/command/ingestion/batch/EventSourceDescriptor.java
Support for publishing messages with payload properties using streamx batch command.
=> DXP-1676 Support for properties in batch publishing

README.md, core/src/test/java/dev/streamx/cli/command/ingestion/publish/PublishCommandTest.java, core/src/test/java/dev/streamx/cli/command/ingestion/publish/PublishPayloadCommandTest.java, core/src/test/java/dev/streamx/cli/command/ingestion/unpublish/UnpublishCommandTest.java, pom.xml
* **Non-braking change**: Bump StreamX version 
* **Non-braking change**: Bump Ingestion Client version
=> [DXP-1288] Support multiple topics per incoming channel

core/src/main/java/dev/streamx/cli/command/ingestion/IngestionMessageJsonFactory.java, core/src/main/java/dev/streamx/cli/command/ingestion/batch/BatchCommand.java, core/src/main/java/dev/streamx/cli/command/ingestion/batch/EventSourceDescriptor.java
Restore of discarded commit using force push
=> [DXP-1676] Restore: Support for properties in batch publishing

README.md, core/src/main/java/dev/streamx/cli/command/ingestion/IngestionMessageJsonFactory.java, core/src/main/java/dev/streamx/cli/command/ingestion/batch/BatchCommand.java, core/src/main/java/dev/streamx/cli/command/ingestion/batch/EventSourceDescriptor.java, core/src/test/java/dev/streamx/cli/command/ingestion/publish/PublishCommandTest.java, core/src/test/java/dev/streamx/cli/command/ingestion/publish/PublishPayloadCommandTest.java, core/src/test/java/dev/streamx/cli/command/ingestion/unpublish/UnpublishCommandTest.java, distribution/pom.xml, pom.xml
Restore of discarded commit using force push
=> [DXP-1288] Restore: Support multitopic incoming channels

pom.xml
bump streamx version to 1.0.10
=> [DXP-1722] StreamX fail to run on apple M4

core/pom.xml, pom.xml
=> [DXP-1729] bump streamx-operator version to 0.0.12

core/src/main/java/dev/streamx/cli/command/dev/DevCommand.java, core/src/main/java/dev/streamx/cli/command/meshprocessing/MeshWatcher.java
* **Non-braking change**: Fix running `streamx dev` for mesh located in current directory
=> [DXP-1725] Fix running `streamx dev` for mesh located in current directory

core/src/main/java/dev/streamx/cli/command/ingestion/IngestionArgumentConfig.java, core/src/main/java/dev/streamx/cli/command/ingestion/PayloadProcessingConfig.java
* **Non-braking change**: Maven 3.9.9 build fix.
=> [DXP-1660] Fix Maven 3.9.9 build

core/src/main/java/dev/streamx/cli/command/ingestion/IngestionMessageJsonFactory.java, core/src/main/java/dev/streamx/cli/command/ingestion/publish/PublishCommand.java, core/src/test/java/dev/streamx/cli/command/ingestion/IngestionArgumentsValidationTest.java, core/src/test/java/dev/streamx/cli/command/ingestion/publish/PublishPayloadCommandTest.java
Here give description of the changes you've made in this pull request focusing on what is added or changed. 
For example:
* **Non-braking change**: Added support for publishing with properties
=> [DXP-1336] Publishing with properties

core/pom.xml, distribution/pom.xml, e2e-tests/pom.xml, entrypoint/pom.xml, pom.xml
* **Non-braking change**: Bump CLI version to match StreamX docs version.
=> [DXP-1821] Bump CLI version

core/src/main/java/dev/streamx/cli/util/os/CmdCommandStrategy.java, e2e-tests/src/main/java/dev/streamx/cli/test/tools/terminal/command/CmdCommandStrategy.java
* **Non-braking change**: Fix `streamx init` on Windows.
=> [DXP-1821] Fix `streamx init` on Windows

core/pom.xml, core/src/main/java/dev/streamx/cli/command/dev/DashboardContainer.java, core/src/main/java/dev/streamx/cli/command/dev/DashboardRunner.java, core/src/main/java/dev/streamx/cli/command/dev/DevCommand.java
* **Non-braking change**: Loading service metadata for Dashboards from project localization and mesh localization.
=> [DXP-1961] Loading service metadata for Dashboards from project localization and mesh localization.
